apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment/first-program-deploy.yaml
namespace: default
images:
- name: europe-central2-docker.pkg.dev/asi-gke-dev/asi-gke-repos/first-program
  newTag: dog
